// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:habit_flow/core/models/sync_status.dart';
import 'package:habit_flow/features/auth/models/user/user.dart';
import 'package:habit_flow/features/habits/models/habits/habit.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(SyncStatusAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(SyncStatusAdapter());
    registerAdapter(UserAdapter());
  }
}
